name: "Build OSAL Documentation (API Guide)"

on:
  push:
  pull_request:

jobs:

  #Check for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action.
  check-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build-osal-apiguide:
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Install Dependencies
        run: sudo apt-get install doxygen graphviz -y

      - name: Checkout submodule
        uses: actions/checkout@v3

      - name: Set up for build
        run: |
          cp Makefile.sample Makefile
          make prep

      - name: Build OSAL API Guide
        run: |
          make osal-apiguide 2>&1 > make_osal-apiguide_stdout.txt | tee make_osal-apiguide_stderr.txt
          mv build/docs/osal-apiguide-warnings.log osal-apiguide-warnings.log

      - name: Archive Osal Guide Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: OSAL Guide Artifacts
          path: |
            make_osal-apiguide_stdout.txt
            make_osal-apiguide_stderr.txt
            osal-apiguide-warnings.log

      - name: Error Check
        run: |
          if [[ -s make_osal-apiguide_stderr.txt ]]; then
            cat make_osal-apiguide_stderr.txt
            exit -1
          fi

      - name: Warning Check
        run: |
          if [[ -s osal-apiguide-warnings.log ]]; then
            cat osal-apiguide-warnings.log
            exit -1
          fi
